### ISSUE TITLE
Adding `expand_x=True` will help your Multline look nicer

### ISSUE THREAD

**Issue by PySimpleGUI** [thelocomotion/GloriousProtonManager#12]
If you enable the `expand_x` when making your Multline element, it will automatically size itself, in the  X-direction, to fit the container/window. 

https://github.com/thelocomotion/GloriousProtonManager/blob/5740381f06f5bb6ef655421f1d7041f85ee6d86f/src/GloriousProtonManager/gpm.py#L118

**Comment by thelocomotion** [comment]
Hmm.. I tried it and it doesn't seem to have any effect on the X axis of the Multiline element

**Comment by PySimpleGUI** [comment]
If inside of a "container" element, that container also needs the expand_x.

**Comment by thelocomotion** [comment]
Definitely looking much better! Thanks for the recommendation :)

Adding expand_x or y to other elements also helped with having some consistency across distributions. I added both expands to the frames and now both Fedora and Ubuntu at least look nearly identical

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/178108918-298ee16d-b152-4a37-a89d-5e165303f2c5.png)

Yeah!  There you go!  Nice job applying it to other parts of the project.  It's sort of required to some extent if the window is going to be able to resized either by your code or by the user.

![image](https://user-images.githubusercontent.com/46163555/178108904-ce80a3b6-26c2-48cc-9352-3aae2729f20d.png) it!

The Demo Browser is a good example of elements like the Listbox and Multiple expanding as the window is resized.  It's a bit unusual, however, as I used a `Pane` element too (perhaps overkill upon reflection).

![explorer_t6rxpzjMms](https://user-images.githubusercontent.com/46163555/178109039-b9ffc947-28f9-4444-b501-0df60568fe16.gif)

**Comment by PySimpleGUI** [comment]
It's really helpful to me to understand my users... can I ask a couple of questions?  Totally optional.... not going to be offended if you pass...

There is no implication behind them.  For example:

Have you written a GUI program ever before in any language?
(doesn't mean I think you've made a crappy program, or are showing you have or haven't.... I haven't a clue which is why I'm asking)

How long did it take you from deciding to make this program until you had a version of it up and working "reasonably well"?

Was there any particular PySimpleGUI resource that you found the most helpful during development?

It helps to hear from users what their experience in making something was like.  It gives me an opportunity to improve.   That said, there are currently over 650 open Issues in the PySimpleGUI GitHub, so I know there are a TON of ways it can be better, but I find it valuable to hear from users from time to time in a bigger picture way.

**Comment by thelocomotion** [comment]
@PySimpleGUI 
No worries! Ask away!

It's impressive that you are so active in the community, even for super small projects like mine :)

To answer your questions:
- This is literally the first Python project I ever worked on haha. I work in the IT field as a DevOps/Automation Engineer but I haven't been exposed much to programming (I don't consider tools like Ansible and such programming per se, even tho some people do?). I READ code in the past for specific projects at work, just never implemented something myself. This felt like a really good opportunity to prove myself that I can code to a certain extent. Now I'm super hooked!
- I put between 5/7 hours into this for 5 days or so. Getting a functional app took me maybe 3 days, creating the UI took me 2. Last week has been spent fixing bugs and cleaning up things to make this a more presentable option for people looking to jump into gaming on Linux.
- To be honest, even though I go back to the documentation all the time, I found it a bit confusing? At least for someone like me. I found really useful the first code block to create a basic window but from there I think I took the 'trial and error' approach + Stackoverflow and just Googling everything

All in all, after researching on what the best and simplest tool was to create a UI for some Python app, yours came on top on most sites, especially reddit. I cannot tell yet how much easier this was compared to implementing the UI in something like GTK/Qt since I never tried that but if someone without that much exposure in coding was able to get something like this up and running, that means you're doing some great work :100:
